version: '2'

services:

  ms-boilerplate:
    image: redleap/ms-boilerplate
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 3000:3000

  ms-boilerplat-service2:
    image: redleap/ms-boilerplate
    environment:
      - PORT=4000
      - ROOT_URL=http://localhost:4000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 4000:4000

  ms-boilerplat-service3:
    image: redleap/ms-boilerplate
    environment:
      - PORT=5000
      - ROOT_URL=http://localhost:5000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 5000:5000

  ms-boilerplat-service4:
    image: redleap/ms-boilerplate
    environment:
      - PORT=6000
      - ROOT_URL=http://localhost:6000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 6000:6000

  ms-boilerplat-service5:
    image: redleap/ms-boilerplate
    environment:
      - PORT=7000
      - ROOT_URL=http://localhost:7000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 7000:7000

  ms-boilerplat-service6:
    image: redleap/ms-boilerplate
    environment:
      - PORT=8000
      - ROOT_URL=http://localhost:8000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 8000:8000

  ms-boilerplat-service7:
    image: redleap/ms-boilerplate
    environment:
      - PORT=9000
      - ROOT_URL=http://localhost:9000
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 9000:9000

  ms-boilerplat-service8:
    image: redleap/ms-boilerplate
    environment:
      - PORT=9100
      - ROOT_URL=http://localhost:9100
      - MONGO_URL=mongodb://mongo:27017/services
    depends_on:
      - mongo
    ports:
      - 9100:9100


  mongo:
    image: mongo:3.2
    volumes:
      - ./data/db:/data/db
